---
abstract: 'Get assemblies for a project accession'
author:
  - 'Andrew J. Page <ap13@sanger.ac.uk>'
build_requires:
  Env::Path: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.033, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-RetrieveAssemblies
requires:
  File::Path: 0
  Getopt::Long: 0
  Moose: 0
resources:
  homepage: http://www.sanger.ac.uk/
  repository: https://github.com/sanger-pathogens/Bio-RetrieveAssemblies.git
version: 0.0.1
